//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::account::Entity as Account;
pub use super::notification::Entity as Notification;
pub use super::variables::Entity as Variables;
