//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::account::Entity as Account;
pub use super::notification::Entity as Notification;
pub use super::variables::Entity as Variables;
